meta_product_name: "Carbon Bounty"
meta_title: "Carbon Bounty, l'IoT pour l'environnement."
meta_description: "Trouver le meilleur compromis entre efficacité environnementale, économique, technologique et social."
meta_image: "Logo_Carbon_Bounty_im2q3k.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
